# Site Settings
title: JekyllCart
description: A Jekyll Based Shopping Cart Built with simpleCart(js)
avatar: /assets/images/404.jpg
url: https://jekyllsimplecart.pages.dev
modder: DaffaDev
mail: namamu@mail.com
phone: 081386267897
tlp: 021000000
address: Jl. Jalan Rt.0001/00002
note: Toko Sedang Liburan Akhir Zaman
fork: https://github.com/daffadevhosting/JekyllSimpleCart.git

baseurl: 

# Jekyll Configuration
encoding: UTF-8
permalink: /:title/
paginate: 10
paginate_path: "/products/page/:num/"

# Markdown Processing
markdown: kramdown
kramdown:
  input: GFM

# Sass/SCSS settings
sass:
  sass_dir: _sass
  style: compressed

# Custom Collections
collections:
  products:
    output: true

# Collection Defaults
defaults:
- scope:
    type: posts
  values:
    layout: post
- scope:
    type: pages
  values:
    layout: page
- scope:
    type: products
  values:
    layout: product
- scope:
    type: cart
  values:
    layout: cart
- scope:
    type: checkout
  values:
    layout: checkout

# Frontmatter Defaults
sidebar_options:
  - sidebar
  - no-sidebar

# Plugins
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  permalinks:
    categories: '/category/:name/'
    tags: '/tag/:name/'

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# File Handling
# include: [_pages]
exclude: [lib, config.rb, .sass-cache, Capfile, config, log, Rakefile, Rakefile.rb, tmp, Gemfile, Gemfile.lock, README.md, LICENSE.md, node_modules, gulpfile.js, package.json]
